INSTALL_DIRECTORY=/home/tookitaki

IS_SSL_REQUIRED=YES
#if YES, please provide certs and password in kafka section.
##********************************** JAVA  ********************************

JAVA_SERVERS_IP=13.0.0.120,13.0.0.202,13.0.0.239
JAVA_SERVERS_USERNAME=tookitaki
JAVA_AUTH_MECH=KEY
JAVA_SERVER_KEY_LOCATION=/home/tookitaki/.ssh/id_rsa
JAVA_SERVER_PASSWORD=null

##********************************** KAFKA *******************************

KAFKA_SERVERS_IP=ip-13-0-0-120.ec2.internal,ip-13-0-0-202.ec2.internal,ip-13-0-0-239.ec2.internal
KAFKA_SERVERS_USERNAME=tookitaki
KAFKA_AUTH_MECH=KEY
KAFKA_SERVER_KEY_LOCATION=/home/tookitaki/.ssh/id_rsa
KAFKA_SERVER_PASSWORD=null


#Below values are default, user needs to replace these to deploy kafka with ssl.
truststore=/home/tookitaki/certs/kafka.truststore.jks
truststorepasswd=changeme
keystore=/home/tookitaki/certs/kafka.keystore.jks
keystorepasswd=changeme
keypasswd=changeme
